server:
  port: 8080
  servlet:
    context-path: /hotel



spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_web"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2MB